- name: restart ranking
  shell: "{{ item }}"
  with_items:
          - (kill -9 $(ps -ef|grep bin/cms|awk '{print $2}') &)
          - (nohup cmsResourceService -a {{ contestId }}  &)
          - (nohup cmsLogService -c {{ contestId }} &)
