- name: Copy cms.ranking.conf to the destination 
  become: yes
  become_method: su
  become_user: root
  template:
          src: conf.j2
          dest: /usr/local/etc/cms.ranking.conf

- name: copy images to the ranking servers
  copy:
          src: "{{ item }}"
          dest: /var/local/lib/cms/ranking/
  with_items:
          - logo.png
          - flags
            #- faces/*.jpg
  notify: restart ranking

          
