---

– hosts: contestants
  user: root
  vars:
   user_password: “{{ password }}”
   user_name: “{{ username }}”
   is_admin: “{{ admin }}”
  roles:
    – { role: create_contestant ,upassword: “{{ user_password }}”,uusername: “{{ user_name }}”,assigned_role: “{{ is_admin }}”, when: action == “create_user” }
