# Write cms.conf to all workers

- hosts: 172.26.0.2, 172.26.0.5
  remote_user: ansible
  strategy: free
  gather_facts: no

  vars:
          template: workers

  vars_files:
          - /home/sysadmin/ansible-vars/cms
          - /home/sysadmin/ansible-vars/db
  roles:
          - config
