# Write cms.conf to all CMS servers

- hosts: servers
  remote_user: sysadmin
  strategy: free
  gather_facts: no

  vars:
          template: servers

  vars_files:
          - /home/sysadmin/ansible-vars/cms
          - /home/sysadmin/ansible-vars/db
  roles:
          - config
