# Write cms.conf to all CMS servers

- hosts: testworker
  remote_user: ansible
  strategy: free
  gather_facts: no

  vars:
          template: servers

  vars_files:
          - /home/ioiauto/ansible-vars/cms
          - /home/ioiauto/ansible-vars/db
  roles:
          - config
