# Write cms.conf to all workers

- hosts: virtual_w
  remote_user: sysadmin
  strategy: free
  gather_facts: no

  vars:
          template: workers

  vars_files:
          - /home/sysadmin/ansible-vars/cms
          - /home/sysadmin/ansible-vars/db
  roles:
          - config
