- name: Shutdown hosts
  become: yes
  become_method: su
  become_user: root
  command: /sbin/shutdown -h now
  tags: shutdown

- name: Restart hosts
  become: yes
  become_method: su
  become_user: root
  reboot:
          reboot_timeout: 1
  tags: reboot, restart

- name: Start a browser with seat page
  become: yes
  become_method: su
  become_user: root
  script: scripts/open_browser.sh
  tags: browser

- name: Running a script.sh on remote hosts
  become: yes
  become_method: su
  become_user: root
  script: scripts/script.sh
  tags: script

- name: Lock contestant screen
  become: yes
  become_method: su
  become_user: root
  systemd: 
        name: i3lock
        state: started
  tags: lock

- name: Unlock contestant screen
  become: yes
  become_method: su
  become_user: root
  systemd: 
        name: i3lock
        state: stopped
  tags: unlock
  
- name: enable usb
  gather_facts: False
  become: yes
  become_method: su
  become_user: root
  tasks:
  - shell: cp -r /home/ansible/drivers/usb-storage.ko /lib/modules/$(uname -r)/kernel/drivers/usb/storage/usb-storage.ko
  tags: enusb

 
