  - name: Copy cms.conf to the destination 
    become: yes
    become_method: su
    become_user: root
    template:
            src: cms_conf.j2
            dest: /usr/local/etc/cms.conf

  - name: Restart CMS Services
    become: yes
    become_method: su
    become_user: root
    systemd: 
      name: "{{item}}" 
      state: restarted
    with_items:
            - 'cmsResource@{{contestId}}'
            - 'cmsLog@{{contestId}}'

