  - name: Copy cms.conf to the destination 
    become: yes
    become_method: su
    become_user: root
    template:
            src: cms_{{template}}.j2
            dest: /usr/local/etc/cms.conf

  - name: Restart CMS services
    shell: "{{ item }}"
    with_items:
            - (kill -9 $(ps -ef|grep bin/cms|awk '{print $2}') &) 
            - (nohup cmsResourceService -a {{contestId}} &)
            - (nohup cmsLogService -c {{contestId}} &)
