  - name: Copy cms.conf to the destination 
    become: yes
    become_method: su
    become_user: root
    template:
            src: cms_{{template}}.j2
            dest: /usr/local/etc/cms.conf

  - name: Kill CMS services
    shell: ps -ef | grep bin/cms | awk '{print $2}' | xargs kill -9
    ignore_errors: true
    async: 3

  - name: Restart CMS services
    shell: "{{ item }}"
    async: 10
    with_items:
            - (cmsResourceService -a {{contestId}} &)
            - (cmsLogService -c {{contestId}} &)
